export const products = [
  {
    id: 1,
    desc: "Lindt Floral Edition Pink or Blue GOLD BUNNY Milk Chocolate Easter Bunny, 200g",
    original_price: 14.99,
    sales: 11.99,
    image: "/images/img4.jpg",
    category: "Bunny",
  },
  {
    id: 2,
    desc: "Lindt LINDOR Strawberries and Cream White Chocolate Truffles, 150-Gram Bag",
    original_price: 9.29,
    sales: 0,
    image: "/images/img3.jpg",
    category: "White",
  },
  {
    id: 3,
    desc: "Lindt LINDOR Milk and White Chocolate Valentine's Truffles, 150-Gram Bag",
    original_price: 9.29,
    sales: 0,
    image: "/images/img2.jpg",
    category: "Milk & White",
  },
  {
    id: 4,
    desc: "Lindt LINDOR Dark Chocolate Strawberry Truffles, 150-Gram Bag",
    original_price: 9.29,
    sales: 0,
    image: "/images/img1.jpg",
    category: "Dark",
  },
  {
    id: 5,
    desc: "Lindt GOLD BUNNY Easter Chocolate Variety Pack, 700g",
    original_price: 55.00,
    sales: 44.00,
    image: "/images/img5.jpg",
    category: "Bunny",
  },
  {
    id: 6,
    desc: "Lindt GOLD BUNNY Family Easter Chocolate Bundle, 350g",
    original_price: 29.00,
    sales: 23.20,
    image: "/images/img6.jpg",
    category: "Bunny",
  },
  {
    id: 7,
    desc: "Lindt LINDOR Caramel & Sea Salt Milk Chocolate Bar, 100g",
    original_price: 9.29,
    sales: 0,
    image: "/images/img7.jpg",
    category: "Milk",
  },
  {
    id: 8,
    desc: "Lindt Premium Hot Chocolate Mix, 300 Grams",
    original_price: 9.99,
    sales: 7.49,
    image: "/images/img8.jpg",
    category: "Mix",
  },
  {
    id: 9,
    desc: "Lindt Vegan Original Chocolate Bar, 100 Grams",
    original_price: 6.79,
    sales: 0,
    image: "/images/img9.jpg",
    category: "Vegan",
  },
  {
    id: 10,
    desc: "Lindt EXCELLENCE Cranberry & Nuts Dark Chocolate Bar, 100 Grams",
    original_price: 14.99,
    sales: 11.99,
    image: "/images/img10.jpg",
    category: "Dark",
  },
  {
    id: 11,
    desc: "Lindt EXCELLENCE 100% Cacao Orange Dark Chocolate Bar, 50 Grams",
    original_price: 5.49,
    sales: 0,
    image: "/images/img11.jpg",
    category: "Dark",
  },
  {
    id: 12,
    desc: "Lindt LINDOR Assorted Dark Chocolate Truffles, 240-Gram Bag",
    original_price: 13.49,
    sales: 0,
    image: "/images/img12.jpg",
    category: "Dark",
  },
  {
    id: 13,
    desc: "Lindt Gourmet Truffles Gift Box, 192 Grams",
    original_price: 25.79,
    sales: 21.92,
    image: "/images/img13.jpg",
    category: "Mix",
  },
  {
    id: 14,
    desc: "Lindt LINDOR Pistachio Milk Chocolate Truffles Bag, 150 Grams",
    original_price: 9.29,
    sales: 0,
    image: "/images/img14.jpg",
    category: "Milk",
  },
  {
    id: 15,
    desc: "Lindt LINDOR Spring Edition Assorted Chocolate Truffles Gift Box, 156 Grams",
    original_price: 13.49,
    sales: 11.47,
    image: "/images/img15.jpg",
    category: "Mix",
  },
  {
    id: 16,
    desc: "Lindt LINDOR White Chocolate Truffles, 150-Gram Bag",
    original_price: 9.29,
    sales: 0,
    image: "/images/img16.jpg",
    category: "White",
  },
  {
    id: 17,
    desc: "Lindt LINDOR Milk Chocolate Mini Eggs, 100-Gram Bag",
    original_price: 5.29,
    sales: 4.23,
    image: "/images/img17.jpg",
    category: "Milk",
  },
]